# Generated by Django 5.0.7 on 2024-08-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0003_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
