# Generated by Django 5.0.7 on 2024-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0005_alter_team_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='top30',
            field=models.BooleanField(default=True),
        ),
    ]
