# Generated by Django 5.0.7 on 2024-08-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0007_remove_playerstats_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='trophies',
        ),
    ]
