# Generated by Django 5.0.7 on 2024-08-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0008_remove_playerstats_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='majorWin',
            field=models.BooleanField(default=False),
        ),
    ]
