# Generated by Django 5.0.7 on 2024-08-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0009_playerstats_majorwin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='majorWin',
            field=models.IntegerField(default=0),
        ),
    ]
