# Generated by Django 5.0.7 on 2024-08-19 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0010_alter_playerstats_majorwin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guessr.player')),
            ],
        ),
    ]
