# Generated by Django 5.0.7 on 2024-08-20 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0011_dailyplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='g1g',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='g2g',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='g3g',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='g4g',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='g5g',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='g6g',
        ),
        migrations.AddField(
            model_name='userstats',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='guessr.dailyplayer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstats',
            name='guesses',
            field=models.IntegerField(default=6),
        ),
    ]
