# Generated by Django 5.0.7 on 2024-08-22 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0012_remove_userstats_g1g_remove_userstats_g2g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='guessr.region'),
        ),
    ]
