# Generated by Django 5.0.7 on 2024-08-26 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessr', '0013_player_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firepower', models.IntegerField(default=0)),
                ('entrying', models.IntegerField(default=0)),
                ('trading', models.IntegerField(default=0)),
                ('opening', models.IntegerField(default=0)),
                ('clutching', models.IntegerField(default=0)),
                ('sniping', models.IntegerField(default=0)),
                ('utility', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='guessr.player')),
            ],
        ),
    ]
